### ISSUE TITLE
夹杂韩语的行距

### ISSUE THREAD

**Issue by Bril87** [lxgw/LxgwXiHei#16]
![Screenshot_20240724_224011_com.netease.cloudmusic_edit_33660469740176.jpg](https://github.com/user-attachments/assets/eedf3aec-3090-4677-8f43-f9ca6e85b3a7)

XiHeiCL，在移动终端上使用有韩语时两行显示不全

**Comment by lxgw** [comment]
本字体不支持韩语，也没有补全韩语的计划，抱歉。
